# Datasource and JPA configuration to be used for using the same tokenstore as the authorization server for
# the defined resource server. Note that there can't be 2 different root nodes, so datasource falls under the "spring" node.
spring:
  profiles: cloud


 routes:
    po-job: /api/job/**  
    asn-service: /api/asn/**
    po-service: /api/po/**
    web-portal: /**
 

eureka:
  client:
    serviceUrl:
      defaultZone: http://supplier-collaboration-eureka.azurewebsites.net/eureka/
