spring:
  profiles:
    active: default
---
spring:
  profiles: development
server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: default
#server:
 # port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://supplier-collaboration-eureka.azurewebsites.net/eureka/
